runtime: python27
api_version: 1
threadsafe: true
service: photoalbum

handlers:
- url: /.*
  script: main.app

env_variables:
  LANG_TAG: 'en'
  TIMESTAMP_TZ: 'US/Eastern'
  BUCKET: 'albumsapp'

libraries:
- name: ssl
  version: latest
